name: "Build Agent EL9,EL10,U22"

on: # checkov:skip=CKV_GHA_7 User input is controlled and intended for tag/branch selection
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"
      branch:
        description: "Branch to use of siterm code?"
        default: "master"
        type: "string"
      startupbranch:
        description: "Branch to use of siterm-startup (build base)?"
        default: "master"
        type: "string"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        osver: [el9, el10, u22]
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v5
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup
        ref: ${{ github.event.inputs.startupbranch }}

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: docker login quay.io
      env:
        QUAY_USER: ${{secrets.QUAY_USER}}
        QUAY_PASSWORD: ${{secrets.QUAY_PASSWORD}}
      run: docker login quay.io -u $QUAY_USER -p $QUAY_PASSWORD 

    - name: Build the BASE Docker for ${{ matrix.osver }}
      run: |
        cd siterm-startup/helpers/base_images/agent/
        docker build . --file Dockerfile-${{ matrix.osver }} \
          --tag sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-${{ matrix.osver }} \
          --tag sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-${{ matrix.osver }} \
          --tag quay.io/sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-${{ matrix.osver }} \
          --tag quay.io/sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-${{ matrix.osver }}

    - name: Docker Push BASE Image to DockerHub for ${{ matrix.osver }}
      run: |
        docker push sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-${{ matrix.osver }}
        docker push sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-${{ matrix.osver }}

    - name: Docker Push BASE Image to Quay.io for ${{ matrix.osver }}
      run: |
        docker push quay.io/sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-${{ matrix.osver }}
        docker push quay.io/sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-${{ matrix.osver }}

    - name: Tag base as bare (only for el10)
      if: matrix.osver == 'el10'
      run: |
        docker tag quay.io/sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-el10 quay.io/sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}
        docker push quay.io/sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}
        docker tag sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}-el10 sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}
        docker push sdnsense/sitermagentbase:${{ github.event.inputs.buildtag }}

    - name: Build the AGENT Docker for ${{ matrix.osver }}
      run: | 
        cd siterm-startup/agent/container-build-files/
        docker build . --file Dockerfile-${{ matrix.osver }} \
          --build-arg RELEASE=${{ github.event.inputs.buildtag }}-${{ matrix.osver }} \
          --build-arg GITBR=${{ github.event.inputs.branch }} \
          --tag sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-${{ matrix.osver }} \
          --tag sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-${{ matrix.osver }} \
          --tag quay.io/sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-${{ matrix.osver }} \
          --tag quay.io/sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-${{ matrix.osver }}

    - name: Docker Push AGENT Image to DockerHub for ${{ matrix.osver }}
      run: |
        docker push sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-${{ matrix.osver }}
        docker push sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-${{ matrix.osver }}

    - name: Docker Push AGENT Image to Quay.io for ${{ matrix.osver }}
      run: |
        docker push quay.io/sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-${{ matrix.osver }}
        docker push quay.io/sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-${{ matrix.osver }}

    - name: Tag agent as bare (only for el10)
      if: matrix.osver == 'el10'
      run: |
        docker tag quay.io/sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-el10 quay.io/sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}
        docker push quay.io/sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}
        docker tag sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}-el10 sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}
        docker push sdnsense/siterm-agent:${{ github.event.inputs.buildtag }}